const PAKOT = {
    individ: [
        {
            id: 'individ_baze',
            emri: 'Bazë',
            zona: 'KS',
            shuma: '20,000',
            hospitalore: '100%',
            ambulatore: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            shtatzania: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            dentar: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            optik: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            degim: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            psikiatrik: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            fizioterapi: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            autoambulanca: '100% deri në € 50',
            aksidentit: '100% deri në € 5,000',
            onkologjike: '100% deri në € 5,000',
            primi_madh: '270.00',
            primi_femije: ''
        },
        {
            id: 'individ_standard',
            emri: 'Standard',
            zona: 'KS, ALB',
            shuma: '30,000',
            hospitalore: '100%',
            ambulatore: '80% deri në € 500',
            shtatzania: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            dentar: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            optik: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            degim: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            psikiatrik: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            fizioterapi: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            autoambulanca: '100% deri në € 100',
            aksidentit: '100% deri në € 10,000',
            onkologjike: '100% deri në € 10,000',
            primi_madh: '380.00',
            primi_femije: ''
        },
        {
            id: 'individ_standard_plus',
            emri: 'Standard Plus',
            zona: 'KS, ALB, NMK, MNE, SRB, SLO, HR',
            shuma: '50,000',
            hospitalore: '100%',
            ambulatore: '80% deri në € 1,000',
            shtatzania: '80% deri në € 800',
            dentar: '80% deri në € 80',
            optik: '80% deri në € 60',
            degim: '80% deri në € 100',
            psikiatrik: '80% deri në € 100',
            fizioterapi: '80% deri në € 50',
            autoambulanca: '100% deri në € 150',
            aksidentit: '100% deri në € 15,000',
            onkologjike: '100% deri në € 15,000',
            primi_madh: '450.00',
            primi_femije: ''
        }
    ],
    familje_biznes: [
        {
            id: 'fb_baze',
            emri: 'Bazë',
            zona: 'KS',
            shuma: '20,000',
            hospitalore: '100%',
            ambulatore: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            shtatzania: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            dentar: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            optik: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            degim: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            psikiatrik: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            fizioterapi: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            autoambulanca: '100% deri në € 50',
            aksidentit: '100% deri në € 5,000',
            onkologjike: '100% deri në € 5,000',
            primi_madh: '15.00',
            primi_femije: '13.00'
        },
        {
            id: 'fb_standard',
            emri: 'Standard',
            zona: 'KS, ALB',
            shuma: '30,000',
            hospitalore: '100%',
            ambulatore: '80%',
            shtatzania: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            dentar: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            optik: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            degim: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            psikiatrik: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            fizioterapi: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            autoambulanca: '100% deri në € 100',
            aksidentit: '100% deri në € 10,000',
            onkologjike: '100% deri në € 10,000',
            primi_madh: '20.00',
            primi_femije: '18.00'
        },
        {
            id: 'fb_stanard',
            emri: 'Stanard',
            zona: 'KS, ALB',
            shuma: '30,000',
            hospitalore: '100%',
            ambulatore: '80%',
            shtatzania: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            dentar: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            optik: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            degim: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            psikiatrik: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            fizioterapi: 'Nuk mbulohen; Zbritje brenda Rjjetit Mjekësor sipas marrëvshjeve me institucionet',
            autoambulanca: '100% deri në € 100',
            aksidentit: '100% deri në € 10,000',
            onkologjike: '100% deri në € 10,000',
            primi_madh: '20.00',
            primi_femije: '18.00'
        },
        {
            id: 'fb_standard_plus',
            emri: 'Standard Plus',
            zona: 'KS, ALB, NMK, MNE, SRB, SLO, HR',
            shuma: '50,000',
            hospitalore: '100%',
            ambulatore: '80%',
            shtatzania: '80% deri në € 1,000',
            dentar: '80% deri në € 100',
            optik: '80% deri në € 80',
            degim: '80% deri në € 100',
            psikiatrik: '80% deri në € 100',
            fizioterapi: '80% deri në € 70',
            autoambulanca: '100% deri në € 150',
            aksidentit: '100% deri në € 15,000',
            onkologjike: '100% deri në € 15,000',
            primi_madh: '30.00',
            primi_femije: '27.00'
        },
        {
            id: 'fb_premium',
            emri: 'Premium',
            zona: 'KS, ALB, NMK, MNE, SRB, SLO, HR',
            shuma: '70,000',
            hospitalore: '100%',
            ambulatore: '80%',
            shtatzania: '80% deri në € 1,200',
            dentar: '80% deri në € 120',
            optik: '80% deri në € 80',
            degim: '80% deri në € 120',
            psikiatrik: '80% deri në € 120',
            fizioterapi: '80% deri në € 100',
            autoambulanca: '100% deri në € 200',
            aksidentit: '100% deri në € 20,000',
            onkologjike: '100% deri në € 20,000',
            primi_madh: '35.00',
            primi_femije: '32.00'
        },
        {
            id: 'fb_silver',
            emri: 'Silver',
            zona: 'KS, ALB, NMK, MNE, SRB, SLO, HR, TR',
            shuma: '100,000',
            hospitalore: '100%',
            ambulatore: 'KS, ALB, NMK, MNE, SRB, SLO, HR: 80%; TR: 80% deri në € 2,000',
            shtatzania: '80% deri në € 1,500',
            dentar: '80% deri në € 150',
            optik: '80% deri në € 100',
            degim: '80% deri në € 150',
            psikiatrik: '80% deri në € 150',
            fizioterapi: '80% deri në € 150',
            autoambulanca: '100% deri në € 300',
            aksidentit: '100% deri në € 25,000',
            onkologjike: '100% deri në € 30,000',
            primi_madh: '60.00',
            primi_femije: '55.00'
        },
        {
            id: 'fb_gold',
            emri: 'Gold',
            zona: 'Gjitha bota përjashtuar SHBA, Kanada dhe Zvicra',
            shuma: '200,000',
            hospitalore: '100%',
            ambulatore: 'KS, ALB, NMK, MNE, SRB, SLO, HR: 100%; Shtetet tjera: 100% deri në € 5,000',
            shtatzania: '100% deri në € 2,000',
            dentar: '100% deri në € 200',
            optik: '100% deri në € 150',
            degim: '100% deri në € 200',
            psikiatrik: '100% deri në € 200',
            fizioterapi: '100% deri në € 200',
            autoambulanca: '100% deri në € 400',
            aksidentit: '100% deri në € 30,000',
            onkologjike: '100% deri në € 50,000',
            primi_madh: '100.00',
            primi_femije: '90.00'
        }
    ]
};